eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}   // DOCKER_LOCAL_URL=host.docker.internal
      defaultZone: http://${DOCKER_LOCAL_URL:localhost}:8761/eureka

okta:
  oauth2:
    issuer: https://dev-66170542.okta.com/oauth2/default

spring:
  zipkin:
    baseUrl: http://zipkin-svc:9411
